{"error": "Invalid number of args", "args": ["simulator.py", "100", "/simulator/trace_files/kth_sp2.json", "100", "dax:/simulator/workflows/CYBERSHAKE_250_360000.dax", "104400", "zhang:noglobal:nobsearch:prediction", "conservative_bf", "--wrench-no-log"]}